name: week-7-ci

on:
  push:
    branches:
      - 'course-04-2023-week-7'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build app seldon
        uses: docker/build-push-action@v2
        with:
          context: week-7/
          file: week-7/Dockerfile
          push: true
          target: app-seldon
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/app-seldon-monitoring-week-7:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/app-seldon-monitoring:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/app-seldon-monitoring:buildcache,mode=max